name: Push
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 9.8.0
      - name: Install
        run: npm ci
      - name: Run ESLint on changed files
        uses: jackton1/eslint-changed-files@v4
        with:
          config-path: '/.github/.eslintrc'
          ignore-path: '/.github/.eslintignore'
          extensions: 'ts,tsx,js,jsx'
          extra-args: '--max-warnings=0'
